# Generated by Django 4.0 on 2023-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_choice1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_choice3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_choice4',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='questions', to='myapp.Choice'),
        ),
    ]
